# Generated by Django 5.1.7 on 2025-03-10 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('firstname', models.TextField()),
                ('lastname', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
