# Generated by Django 5.1.7 on 2025-04-03 19:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_team_employee_holiday_balance_employee_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('max_absences', models.IntegerField(default=1)),
                ('year_holiday_number', models.IntegerField(default=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HolidaysRequest',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('max_absences', models.IntegerField(default=1)),
                ('year_holiday_number', models.IntegerField(default=15)),
                ('holydays_begin', models.DateField()),
                ('holydays_end', models.DateField()),
                ('status', models.CharField(choices=[('V', 'Validé'), ('R', 'Refusé'), ('R', 'En traitement')], default='R', max_length=1)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
