# Generated by Django 5.1.7 on 2025-04-03 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_settings_holidaysrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='holidaysrequest',
            old_name='holydays_begin',
            new_name='holidays_begin',
        ),
        migrations.RenameField(
            model_name='holidaysrequest',
            old_name='holydays_end',
            new_name='holidays_end',
        ),
    ]
