# Generated by Django 5.1.7 on 2025-04-04 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_holydays_begin_holidaysrequest_holidays_begin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='holidaysrequest',
            name='status',
            field=models.CharField(choices=[('V', 'Validé'), ('R', 'Refusé'), ('I', 'En traitement')], default='I', max_length=1),
        ),
    ]
