# Generated by Django 5.1.7 on 2025-04-08 02:17

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_employee_is_admin_alter_holidaysrequest_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacationType',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
                ('max_duration', models.IntegerField(blank=True, null=True)),
                ('justification_required', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('proof_required', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='hiring_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='holidaysrequest',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='holidaysrequest',
            name='request_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.CreateModel(
            name='VacationBalance',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('balance', models.IntegerField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacation_balance', to=settings.AUTH_USER_MODEL)),
                ('vacation_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vacation_balance', to='core.vacationtype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='holidaysrequest',
            name='vacation_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vacation_type', to='core.vacationtype'),
        ),
        migrations.CreateModel(
            name='VacationValidation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('validation_date', models.DateField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('decision', models.CharField(choices=[('V', 'Validé'), ('R', 'Refusé'), ('I', 'En traitement')], default='I', max_length=1)),
                ('reason', models.TextField(blank=True, null=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacation_validation', to=settings.AUTH_USER_MODEL)),
                ('vacation_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vacation_validation', to='core.holidaysrequest')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
