# Generated by Django 5.1.7 on 2025-04-08 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_vacationtype_proof_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationFrontEnd',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('vue', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.holidaysrequest')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
