# Generated by Django 5.1.7 on 2025-04-08 16:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_notificationfrontend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationfrontend',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
