# Generated by Django 5.1.7 on 2025-04-08 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_notificationfrontend_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('level', models.CharField(choices=[('1', 'Débutant'), ('2', 'Intermédiaire'), ('3', 'Avancé'), ('4', 'Expert')], default='1', max_length=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='employee_acquired_skills', to='core.skills'),
        ),
    ]
