# Generated by Django 5.1.7 on 2025-04-09 03:21

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_skills_employee_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('acquired_skills', models.ManyToManyField(blank=True, related_name='acquired_skills', to='core.skills')),
                ('prerequisite_skills', models.ManyToManyField(blank=True, related_name='prerequisite_skills', to='core.skills')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TrainingRegistration',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('registration_date', models.DateField(default=datetime.datetime.now)),
                ('status', models.CharField(choices=[('P', 'Prévue'), ('E', 'En cours'), ('T', 'Terminée'), ('A', 'Annulée')], default='P', max_length=1)),
                ('is_present', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to=settings.AUTH_USER_MODEL)),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='core.training')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
