# Generated by Django 5.1.7 on 2025-04-09 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_training_trainingregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='status',
            field=models.CharField(choices=[('P', 'Prévue'), ('E', 'En cours'), ('T', 'Terminée'), ('A', 'Annulée')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='trainingregistration',
            name='status',
            field=models.CharField(choices=[('V', 'Validé'), ('R', 'Refusé'), ('I', 'En traitement')], default='I', max_length=1),
        ),
    ]
