# Generated by Django 5.1.7 on 2025-04-11 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_training_status_alter_trainingregistration_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingregistration',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
