# Generated by Django 5.1.7 on 2025-04-11 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_notificationfrontend_training_request'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainingregistration',
            old_name='employee',
            new_name='owner',
        ),
    ]
